/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import logic.ListaLetras;
import logic.Lista;
import logic.Principal;

/**
 *
 * @author estadm
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    private Image _imagen;
    private Graphics _gpc;
    private BufferedImage _fondo;
    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal(){
        setExtendedState(MAXIMIZED_BOTH);
        initComponents();
        setSize(350,360);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBIniciar = new javax.swing.JButton();
        jBConfigurar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(_fondo);
        setResizable(false);
        getContentPane().setLayout(null);

        jBIniciar.setBackground(new java.awt.Color(0, 0, 0));
        jBIniciar.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jBIniciar.setForeground(new java.awt.Color(255, 255, 255));
        jBIniciar.setText("INICIAR");
        jBIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(jBIniciar);
        jBIniciar.setBounds(120, 160, 130, 38);

        jBConfigurar.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jBConfigurar.setText("CONFIGURACION");
        jBConfigurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfigurarActionPerformed(evt);
            }
        });
        getContentPane().add(jBConfigurar);
        jBConfigurar.setBounds(120, 220, 130, 42);

        jBSalir.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jBSalir.setText("SALIR");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jBSalir);
        jBSalir.setBounds(120, 280, 130, 39);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/scrabble1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-30, 0, 380, 340);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIniciarActionPerformed
        this.dispose();
        PantallaPlayers pn = new PantallaPlayers();
        pn.setVisible(true);
    }//GEN-LAST:event_jBIniciarActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBConfigurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfigurarActionPerformed
        jBIniciar.setBackground(Color.WHITE);
        jBIniciar.setForeground(Color.BLACK);
        jBConfigurar.setBackground(Color.BLACK);
        jBConfigurar.setForeground(Color.WHITE);
    }//GEN-LAST:event_jBConfigurarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        new Principal();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                
                    new PantallaPrincipal().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConfigurar;
    private javax.swing.JButton jBIniciar;
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
